# Generated by Django 2.2.4 on 2019-08-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='description',
            new_name='content',
        ),
        migrations.AddField(
            model_name='service',
            name='subtitle',
            field=models.CharField(max_length=50, null=True, verbose_name='Subtítulo'),
        ),
    ]
